services:
  ollama:
    image: ollama/ollama:rocm
    ipc: host
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
      - /dev/accel:/dev/accel
    group_add:
      - "${VIDEO_GID:-44}"
      - "${RENDER_GID:-992}"
    security_opt:
      - seccomp=unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-}
