services:
  ollama:
    ports:
      - "11434:11434"
  open-webui:
    ports:
      - "8080:8080"
  homepage:
    ports:
      - "80:3000"
  adminer:
    ports:
      - "${ADMINER_PORT:-8081}:8080"
  n8n:
    ports:
      - "${N8N_PORT:-5678}:5678"
  bookstack:
    ports:
      - "${BOOKSTACK_PORT:-8875}:80"
